apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: opjorr/ci-cd-bsi5
  newTag: 4e88d7bc94055945898a07bfe8657fb3c010481d
